spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:./h2_db;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        fomat_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
    active: prd
logging:
  level:
    root: info
server:
  port: 9999
---
#
# DEV Setting
###########################################
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:./h2_db;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;MODE=MYSQL
    username: sa
    password:
#    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        fomat_sql: true
        use_sql_comments: true
    open-in-view: false
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: info

---
#
# PRD Setting
###########################################

spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/livestudy
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        fomat_sql: true
        use_sql_comments: true
  config:
    activate:
      on-profile: prd
logging:
  level:
    root: info

