spring:
  datasource:
    platform: mariadb
    url: "jdbc:mariadb://project-db.coiip3ibz5kx.ap-northeast-2.rds.amazonaws.com:3306"
    username: admin
    password:
    driver-class-name: org.mariadb.jdbc.Driver
