spring:
  datasource:
    platform: mariadb
    url:
    username: admin
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        fomat_sql: true
        use_sql_comments: true

