INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('1031nice','Dong-Hun','https://github.com/1031nice',1),
	 ('2yeseul','이예슬','https://github.com/2yeseul',1),
	 ('abcdsds','abcdefg','https://github.com/abcdsds',1),
	 ('ahyz0569','Yunok','https://github.com/ahyz0569',1),
	 ('asqwklop12',NULL,'https://github.com/asqwklop12',1),
	 ('awesomeo184','정수현','https://github.com/awesomeo184',1),
	 ('Azderica','Myeonghun Park','https://github.com/Azderica',1),
	 ('azurealstn',NULL,'https://github.com/azurealstn',1),
	 ('binaryyoung','jinyoungLee','https://github.com/binaryyoung',1),
	 ('bingbingpa','opensesame','https://github.com/bingbingpa',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('BrandPark','ParkMinGon (javanitto)','https://github.com/BrandPark',1),
	 ('ChoiGiSung',NULL,'https://github.com/ChoiGiSung',1),
	 ('choiyoungkwon12',NULL,'https://github.com/choiyoungkwon12',1),
	 ('chulphan','chulphan','https://github.com/chulphan',1),
	 ('cmg1411','김민걸','https://github.com/cmg1411',1),
	 ('conyconydev','conyconydev','https://github.com/conyconydev',1),
	 ('cs7998',NULL,'https://github.com/cs7998',1),
	 ('dacapolife87','HyungjuJang','https://github.com/dacapolife87',1),
	 ('damho1104','Damho Lee','https://github.com/damho1104',1),
	 ('daroguzo','Jinoo','https://github.com/daroguzo',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('ddings73','ddings','https://github.com/ddings73',1),
	 ('DDOEUN',NULL,'https://github.com/DDOEUN',1),
	 ('delusidiot','delusidiot','https://github.com/delusidiot',1),
	 ('DevelopJKong',NULL,'https://github.com/DevelopJKong',1),
	 ('devHTak',NULL,'https://github.com/devHTak',1),
	 ('devShLee7017',NULL,'https://github.com/devShLee7017',1),
	 ('devvip',NULL,'https://github.com/devvip',1),
	 ('dmstjd1024','EunSeong.dev','https://github.com/dmstjd1024',1),
	 ('dongyeon94',NULL,'https://github.com/dongyeon94',1),
	 ('doyoung0205',NULL,'https://github.com/doyoung0205',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('enothfif',NULL,'https://github.com/enothfif',1),
	 ('etff',NULL,'https://github.com/etff',1),
	 ('garlickim','garlickim','https://github.com/garlickim',1),
	 ('gcha-kim',NULL,'https://github.com/gcha-kim',1),
	 ('geneaky','HiBs','https://github.com/geneaky',1),
	 ('giyeon95','KIYEON-KIM','https://github.com/giyeon95',1),
	 ('Gomding','Gomding','https://github.com/Gomding',1),
	 ('good-influence',NULL,'https://github.com/good-influence',1),
	 ('gowoonsori','EuiSung','https://github.com/gowoonsori',1),
	 ('haeinoh','HaeinOh','https://github.com/haeinoh',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('haemanlee','Haeman Lee','https://github.com/haemanlee',1),
	 ('haemin-jeong','Haemin Jeong','https://github.com/haemin-jeong',1),
	 ('heewonham','Heewon Ham','https://github.com/heewonham',1),
	 ('hhlyn0328',NULL,'https://github.com/hhlyn0328',1),
	 ('hoi-hoon',NULL,'https://github.com/hoi-hoon',1),
	 ('hojunnnnn',NULL,'https://github.com/hojunnnnn',1),
	 ('honux77','Hoyoung Jung','https://github.com/honux77',1),
	 ('HyangKeunChoi','Choi Hyang Keun','https://github.com/HyangKeunChoi',1),
	 ('hyeonic',NULL,'https://github.com/hyeonic',1),
	 ('inhalin','Kimin','https://github.com/inhalin',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('jadenkim94','jaden94','https://github.com/jadenkim94',1),
	 ('jaeeunis','jaeeunis','https://github.com/jaeeunis',1),
	 ('Jangilkyu','장일규','https://github.com/Jangilkyu',1),
	 ('Jason-time','Jason Time','https://github.com/Jason-time',1),
	 ('JeongJin984',NULL,'https://github.com/JeongJin984',1),
	 ('jigmini','jigmini','https://github.com/jigmini',1),
	 ('jikimee64','WooCheol Kim','https://github.com/jikimee64',1),
	 ('jiwoo-choi',NULL,'https://github.com/jiwoo-choi',1),
	 ('jjone36','Jiwon','https://github.com/jjone36',1),
	 ('JJongSue',NULL,'https://github.com/JJongSue',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('joey3116',NULL,'https://github.com/joey3116',1),
	 ('JongWoonLee',NULL,'https://github.com/JongWoonLee',1),
	 ('jongyeans','Jongyean Park','https://github.com/jongyeans',1),
	 ('joowankim','Joowan Kim','https://github.com/joowankim',1),
	 ('JungHyeokMoon',NULL,'https://github.com/JungHyeokMoon',1),
	 ('Junhan0037','KimJunhan','https://github.com/Junhan0037',1),
	 ('justinnn980','박준철','https://github.com/justinnn980',1),
	 ('jymaeng95','JoonYoung Maeng','https://github.com/jymaeng95',1),
	 ('kdh9428','DaHun','https://github.com/kdh9428',1),
	 ('keunyop','Kevin Lee','https://github.com/keunyop',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('kgc0120','GyuCheol','https://github.com/kgc0120',1),
	 ('KilJaeeun','길재은','https://github.com/KilJaeeun',1),
	 ('kingsubin',NULL,'https://github.com/kingsubin',1),
	 ('KJJ924','JAEJOON KIM','https://github.com/KJJ924',1),
	 ('ksj0109188','Kim Seong Jun','https://github.com/ksj0109188',1),
	 ('ksundong','Dion','https://github.com/ksundong',1),
	 ('kwj1270','KimWooJae','https://github.com/kwj1270',1),
	 ('kyu9',NULL,'https://github.com/kyu9',1),
	 ('kyungjaejang','KyungJae Jang','https://github.com/kyungjaejang',1),
	 ('lee-maru','LEE SEOKMIN','https://github.com/lee-maru',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('LeeGiCheol','LEE GI CHEOL','https://github.com/LeeGiCheol',1),
	 ('LeeJeongSeok','Lee','https://github.com/LeeJeongSeok',1),
	 ('LeeWoooo','이우길','https://github.com/LeeWoooo',1),
	 ('limyeonsoo',NULL,'https://github.com/limyeonsoo',1),
	 ('lkimilhol','lkimilhol','https://github.com/lkimilhol',1),
	 ('Lob-dev','Seokhyun ','https://github.com/Lob-dev',1),
	 ('loosie','jongwon','https://github.com/loosie',1),
	 ('mintheon','MinHyun Lee','https://github.com/mintheon',1),
	 ('mongzza','dami','https://github.com/mongzza',1),
	 ('monkeyDugi',NULL,'https://github.com/monkeyDugi',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('MoonHKLee','이문혁','https://github.com/MoonHKLee',1),
	 ('myBabyGrand',NULL,'https://github.com/myBabyGrand',1),
	 ('nimkoes','nimkoes','https://github.com/nimkoes',1),
	 ('numuduwer','Shin Kim','https://github.com/numuduwer',1),
	 ('Ohzzi','Jihoon Oh','https://github.com/Ohzzi',1),
	 ('oktopman',NULL,'https://github.com/oktopman',1),
	 ('ows3090','WonseokOh','https://github.com/ows3090',1),
	 ('Park-SooYeon','Sooyeon Park','https://github.com/Park-SooYeon',1),
	 ('parker1609','SUNGBUM PARK','https://github.com/parker1609',1),
	 ('parksil0',NULL,'https://github.com/parksil0',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('pej4303','ejpark','https://github.com/pej4303',1),
	 ('pond1029','LEE JAE YEON','https://github.com/pond1029',1),
	 ('redbean88','redbean88','https://github.com/redbean88',1),
	 ('Resilient923','shinkyuchul','https://github.com/Resilient923',1),
	 ('reumongshop',NULL,'https://github.com/reumongshop',1),
	 ('rkdals213','강민형','https://github.com/rkdals213',1),
	 ('rlatmd0829','Seunguk','https://github.com/rlatmd0829',1),
	 ('rockintuna','Jeong-In Lee','https://github.com/rockintuna',1),
	 ('rowanlee92','rowanlee92','https://github.com/rowanlee92',1),
	 ('rshak8912','Seunghak Na','https://github.com/rshak8912',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('s0w0s','woo sung','https://github.com/s0w0s',1),
	 ('salmon2',NULL,'https://github.com/salmon2',1),
	 ('sangwoobae','Bae Sangwoo','https://github.com/sangwoobae',1),
	 ('sellester','Kim Yong Kwan','https://github.com/sellester',1),
	 ('SeungWoo-Oh',NULL,'https://github.com/SeungWoo-Oh',1),
	 ('ShimSeoungChul','scs','https://github.com/ShimSeoungChul',1),
	 ('sinchang1',NULL,'https://github.com/sinchang1',1),
	 ('SJParkkk',NULL,'https://github.com/SJParkkk',1),
	 ('SooJungDev','Soojung Choi','https://github.com/SooJungDev',1),
	 ('sophysophysophysophy','정현주','https://github.com/sophysophysophysophy',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('sskim91','sskim','https://github.com/sskim91',1),
	 ('ssonsh','ssonzk','https://github.com/ssonsh',1),
	 ('sujl95','TheWing','https://github.com/sujl95',1),
	 ('Sungjun-HQ',' Sungjun HWANG','https://github.com/Sungjun-HQ',1),
	 ('sungpillhong','Hong Sung Pill','https://github.com/sungpillhong',1),
	 ('sunnynote','Sunny','https://github.com/sunnynote',1),
	 ('thisisyoungbin','Youngbin Kim','https://github.com/thisisyoungbin',1),
	 ('tocgic','jay.c','https://github.com/tocgic',1),
	 ('UmJaeJeong',NULL,'https://github.com/UmJaeJeong',1),
	 ('Yadon079','Sunwoo Han','https://github.com/Yadon079',1);
INSERT INTO t_user_info (github_id,github_nickname,github_profile_img,status) VALUES
	 ('yangseungin','Seungin Yang','https://github.com/yangseungin',1),
	 ('yeGenieee','Yejin Choi','https://github.com/yeGenieee',1),
	 ('yhh1056','yhh1056','https://github.com/yhh1056',1),
	 ('yky03',NULL,'https://github.com/yky03',1),
	 ('Yo0oN','YoonJeong','https://github.com/Yo0oN',1),
	 ('Youngerjesus','Jeongmin Yeo','https://github.com/Youngerjesus',1),
	 ('youngjinmo','Youngjin Mo','https://github.com/youngjinmo',1),
	 ('younwony','wony9324','https://github.com/younwony',1),
	 ('ysmiler',NULL,'https://github.com/ysmiler',1);