
CREATE TABLE IF NOT EXISTS T_MASTER_CODE
(
    MASTER_CODE CHAR(100) NOT NULL,
    MASTER_DESC TEXT      NOT NULL,
    CONSTRAINT PK_T_CODE PRIMARY KEY (MASTER_CODE)
);

CREATE TABLE IF NOT EXISTS T_COMMON_CODE
(
    CODE         VARCHAR(100)    NOT NULL    ,
    MASTER_CODE  VARCHAR(100)    NOT NULL    ,
    CODE_KR      VARCHAR(100)    NOT NULL    ,
    CODE_DESC    TEXT            NOT NULL    ,
    CODE_ORDER   INT             NOT NULL    ,
    REG_ID       VARCHAR(100)    NOT NULL    ,
    REG_DATE     DATETIME        NOT NULL    ,
    MOD_ID       VARCHAR(100)    NOT NULL    ,
    MOD_DATE     DATETIME        NOT NULL    ,
    MOD_COMMENT  TEXT                        ,
    STATUS       TINYINT(4)      NOT NULL    ,
    CONSTRAINT PK_T_COMMON_CODE PRIMARY KEY (CODE)
);

